management:
  endpoints:
    web:
      base-path: /manage
      exposure:
        include: "*"
        
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate: DEBUG
    org.hibernate.type.descriptor.sql: TRACE
    
spring:
  jpa:
    hibernate:
      ddl-auto: update